// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr7ipIJhUpF3l_QerSMeuLvRd1UTDGnDg',
    appId: '1:20811097061:web:78280d2a6cdab9232d850c',
    messagingSenderId: '20811097061',
    projectId: 'kyoto-express-71566',
    authDomain: 'kyoto-express-71566.firebaseapp.com',
    storageBucket: 'kyoto-express-71566.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtG-RuqXwd6ol2kRENdfV1RpoNgXWcbsg',
    appId: '1:20811097061:android:853eef1fe68b04262d850c',
    messagingSenderId: '20811097061',
    projectId: 'kyoto-express-71566',
    storageBucket: 'kyoto-express-71566.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIr5nnyS1t3h0YwJVeCr40A_88ccT9HG8',
    appId: '1:20811097061:ios:ac089913a6838ac72d850c',
    messagingSenderId: '20811097061',
    projectId: 'kyoto-express-71566',
    storageBucket: 'kyoto-express-71566.appspot.com',
    iosClientId: '20811097061-tkccdov4i0dhi7acgbkahbonn8vpc54m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyotoExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIr5nnyS1t3h0YwJVeCr40A_88ccT9HG8',
    appId: '1:20811097061:ios:ac089913a6838ac72d850c',
    messagingSenderId: '20811097061',
    projectId: 'kyoto-express-71566',
    storageBucket: 'kyoto-express-71566.appspot.com',
    iosClientId: '20811097061-tkccdov4i0dhi7acgbkahbonn8vpc54m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyotoExpress',
  );
}
